QuanLyChiTieu/ViewModels/JarViewModel.cs
namespace QuanLyChiTieu.ViewModels
{
    public class JarViewModel
    {
        public long JarId { get; set; }
        public string JarName { get; set; }
        public decimal TotalIncome { get; set; }
        public decimal TotalExpense { get; set; }
        public decimal TotalAmount => TotalIncome - TotalExpense;
        // Constructor to initialize the properties
        public JarViewModel(long jarId, string jarName)
        {
            JarId = jarId;
            JarName = jarName;
        }

        public JarViewModel() 
        {
            JarId = 0;
            JarName = string.Empty;
            TotalIncome = 0.0m;
            TotalExpense = 0.0m;
        }
    }
}

QuanLyChiTieu/Controllers/JarController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuanLyChiTieu.Models;
using QuanLyChiTieu.ViewModels;
using System.Security.Claims;

namespace QuanLyChiTieu.Controllers
{
    [Authorize]
    public class JarController : Controller
    {

        private readonly QlchiTieuContext _context;

        public JarController(QlchiTieuContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            return View();
        }

        public async Task<IActionResult> _GetJarByMonth(int? month, int? year)
        {
            month ??= DateTime.Now.Month;
            year ??= DateTime.Now.Year;
            var userId = long.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? "0");

            // Tổng thu nhập tháng
            var totalRevenue = await _context.Incomes
                .Where(x => x.UserId == userId && x.IncomeDate.Month == month && x.IncomeDate.Year == year)
                .SumAsync(x => (decimal?)x.TotalAmount) ?? 0;

            // Tổng chi tiêu tháng
            var totalCost = await _context.Expenses
                .Include(x => x.Jar)
                .Where(e => e.Jar.UserId == userId && e.ExpenseDate.Month == month && e.ExpenseDate.Year == year)
                .SumAsync(e => (decimal?)e.Amount) ?? 0;

            var firstDayInMonth = new DateOnly(year.Value, month.Value, 1);
            //Tổng dư trước kỳ
            var totalBefore = (await _context.Incomes
                .Where(x => x.UserId == userId && x.IncomeDate < firstDayInMonth)
                .SumAsync(x => (decimal?)x.TotalAmount) ?? 0)
                -
                (await _context.Expenses
                    .Where(e => e.Jar.UserId == userId && e.ExpenseDate < firstDayInMonth)
                    .SumAsync(e => (decimal?)e.Amount) ?? 0)
                ;

            // Lấy danh sách hũ
            var jars = await _context.ExpenseJars
                .Where(j => j.UserId == userId)
                .Select(j => new JarViewModel
                {
                    JarId = j.JarId,
                    JarName = j.JarName,
                    TotalIncome = _context.IncomeAllocations
                                .Where(ia => ia.JarId == j.JarId && ia.Income.UserId == userId && ia.Income.IncomeDate.Month == month && ia.Income.IncomeDate.Year == year)
                                .Sum(ia => (decimal?)ia.Amount) ?? 0,
                    TotalExpense = _context.Expenses
                                .Where(e => e.JarId == j.JarId && e.ExpenseDate.Month == month && e.ExpenseDate.Year == year)
                                .Sum(e => (decimal?)e.Amount) ?? 0
                })
                .ToListAsync();

            // Gán ViewBag
            ViewBag.TotalRevenue = totalRevenue;
            ViewBag.TotalCost = totalCost;
            ViewBag.TotalBefore = totalBefore;
            ViewBag.Month = month;
            ViewBag.Year = year;
            return PartialView(jars);
        }


        public IActionResult Details()
        {
            return View();
        }
    }
}

QuanLyChiTieu/Views/Jar/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

QuanLyChiTieu/Views/Jar/Index.cshtml
@{
    ViewData["Title"] = "Quản lý hũ chi tiêu";
}
<div class="container mb-3 p-3 position-relative">
    <h2 class="text-center text-uppercase">Danh sách hũ chi tiêu <strong class="month-name text-success"></strong></h2>
    <div class="d-flex align-items-center mt-1 flex-wrap justify-content-center mx-5 mb-3">
        <div class="me-3">
            Chọn tháng:
            <input type="month" id="monthInput" class="form-control" />
        </div>
        <div class="d-flex gap-2 mt-4 me-3">
            <button id="previousMonth" class=" btn btn-primary">
                <i class="bi bi-skip-start-fill"></i>
            </button>
            <button id="currentMonth" class=" btn btn-primary">
                <i class="bi bi-table"></i> Hiện tại
            </button>
            <button id="nextMonth" class=" btn btn-primary">
                <i class="bi bi-skip-end-fill"></i>
            </button>
        </div>

    </div>
    <div class="mb-3 d-none d-md-block">
        <button id="btnAddDesktop" class="btn btn-success">
            <i class="bi bi-plus-lg"></i> Thêm
        </button>
    </div>

    <div id="jarContainer"></div>

    <button id="btnAddMobile"
            class="btn btn-primary rounded-circle shadow-lg d-md-none"
            style="position: fixed; bottom: 20px; right: 20px; width: 60px; height: 60px; z-index:1000;">
        <i class="bi bi-plus-lg fs-4"></i>
    </button>
</div>

@section Links{
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
    
}

@section Scripts {
    <script>
        const monthInput = document.getElementById("monthInput");
        const previousBtn = document.getElementById("previousMonth");
        const currentBtn = document.getElementById("currentMonth");
        const nextBtn = document.getElementById("nextMonth");

        // Hàm khởi tạo giá trị mặc định là tháng hiện tại
        document.addEventListener("DOMContentLoaded", () => {
            const today = new Date();
            const year = today.getFullYear();
            const month = String(today.getMonth() + 1).padStart(2, '0');
            monthInput.value = `${year}-${month}`;
            loadData(); // Gọi hàm load mặc định
        });

        // Sự kiện Previous
        previousBtn.addEventListener("click", () => {
            const date = new Date(monthInput.value + "-01");
            date.setMonth(date.getMonth() - 1);
            updateMonthInput(date);
        });

        // Sự kiện Next
        nextBtn.addEventListener("click", () => {
            const date = new Date(monthInput.value + "-01");
            date.setMonth(date.getMonth() + 1);
            updateMonthInput(date);
        });

        // Sự kiện Hiện tại
        currentBtn.addEventListener("click", () => {
            const today = new Date();
            updateMonthInput(today);
        });

        // Cập nhật giá trị input và gọi hàm load
        function updateMonthInput(date) {
            const year = date.getFullYear();
            const month = String(date.getMonth() + 1).padStart(2, '0');
            monthInput.value = `${year}-${month}`;
            loadData();
        }

        function loadData() {
            var dateValue = document.getElementById("monthInput").value;
            // Kiểm tra xem người dùng đã chọn tháng chưa, nếu chưa chọn tháng hiện tại

            if (!dateValue) {
                const today = new Date();
                const year = today.getFullYear();
                const month = String(today.getMonth() + 1).padStart(2, '0'); // Tháng bắt đầu từ 0
                dateValue = `${year}-${month}`;
            }

            const [year, month] = dateValue.split("-");
            // Cập nhật tiêu đề tháng
            document.querySelector('.month-name').textContent = `tháng ${month} năm ${year}`;
            $.ajax({
                    url: '@Url.Action("_GetJarByMonth", "Jar")',
                    type: 'GET',
                    data: { month: month, year: year },
                    beforeSend: function() {
                        $('#jarContainer').html('<p>Đang tải dữ liệu...</p>');
                    },
                    success: function (result) {
                        $('#jarContainer').html(result);
                    },
                    error: function () {
                        alert('Có lỗi khi tải dữ liệu.');
                    }
                });
        }
        loadData();
    </script>
    <script>
        $(document).ready(function () {
            
            // Nút Thêm desktop
            $('#btnAddDesktop').click(function () {
                showAddOptions();
            });

            // Nút Thêm mobile
            $('#btnAddMobile').click(function () {
                showAddOptions();
            });

            // SweetAlert2 chọn thêm loại giao dịch
            function showAddOptions() {
                Swal.fire({
                    title: 'Bạn muốn thêm gì?',
                    icon: 'question',
                    showCancelButton: true,
                    confirmButtonText: 'Thêm Thu Nhập',
                    cancelButtonText: 'Thêm Chi Tiêu',
                    reverseButtons: true,
                    customClass: {
                        confirmButton: 'btn btn-success',
                        cancelButton: 'btn btn-danger me-3'
                    },
                    buttonsStyling: false
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.href = '@Url.Action("CreateIncome", "Transaction")';
                    } else if (result.dismiss === Swal.DismissReason.cancel) {
                        window.location.href = '@Url.Action("CreateExpense", "Transaction")';
                    }
                });
            }
        });

    </script>
    <script>
       $(document).on('click', '.btnAddJar', function () {
             Swal.fire({
             title: 'Nhập tên hũ',
             input: 'text',
             inputLabel: 'Tên hũ chi tiêu',
             inputPlaceholder: 'VD: Tiết kiệm, Mua sắm...',
             showCancelButton: true,
             confirmButtonText: 'Thêm',
             cancelButtonText: 'Hủy',
             inputValidator: (value) => {
                 if (!value) {
                     return 'Bạn chưa nhập tên hũ!';
                 }
             }
         }).then((result) => {
             if (result.isConfirmed) {
                 const jarName = result.value;

                 // Gửi request POST đến action Create
                 $.ajax({
                     url: '/JarInfo/Create',
                     method: 'POST',
                     data: {
                         JarName: jarName
                     },
                     success: function (response) {
                         showToast('success', 'Thành công');
                          window.location.reload();
                     },
                     error: function (xhr) {
                         Swal.fire('Lỗi', xhr.responseText || 'Không thể thêm hũ.', 'error');
                     }
                 });
             }
         });
        });
    </script>
}

QuanLyChiTieu/Views/Jar/_GetJarByMonth.cshtml
@model List<QuanLyChiTieu.ViewModels.JarViewModel>
@{
    ViewData["Title"] = "_GetJarByMonth";
    var culture = new System.Globalization.CultureInfo("vi-VN");
    decimal totalRevenue = ViewBag.TotalRevenue ?? 0;
    decimal totalCost = ViewBag.TotalCost ?? 0;
    decimal remaining = totalRevenue - totalCost;
    decimal totalBefore = ViewBag.TotalBefore ?? 0;
    var month = ViewBag.Month ?? DateTime.Now.Month;
    var year = ViewBag.Year ?? DateTime.Now.Year;
    var firstDayOfMonth = new DateTime(year, month, 1);
    var lastDayOfMonth = firstDayOfMonth.AddMonths(1).AddDays(-1);
}
<style>
    .card-text{
        white-space: nowrap !important;
    }
</style>
<div class="row g-3 mb-3">
    <!-- Tổng dư trước kỳ -->
    <div class="col-md-3">
        <div class="card text-white bg-warning shadow-sm">
            <div class="card-body">
                <h6 class="card-title">Tổng dư trước tháng</h6>
                <h4 class="card-text fs-2">
                    @totalBefore.ToString("C", culture)
                </h4>
            </div>
        </div>
    </div>
    <!-- Tổng thu nhập -->
    <div class="col-md-3">
        <div class="card text-white bg-primary shadow-sm">
            <div class="card-body">
                <h6 class="card-title">Tổng thu nhập</h6>
                <h4 class="card-text fs-2">
                    @totalRevenue.ToString("C", culture)
                </h4>
            </div>
        </div>
    </div>

    <!-- Tổng chi tiêu -->
    <div class="col-md-3">
        <div class="card text-white bg-danger shadow-sm">
            <div class="card-body">
                <h6 class="card-title">Tổng chi tiêu</h6>
                <h4 class="card-text fs-2">
                    @totalCost.ToString("C", culture)
                </h4>
            </div>
        </div>
    </div>

    <!-- Còn lại -->
    <div class="col-md-3">
        <div class="card text-white @(remaining >= 0 ? "bg-success" : "bg-danger") shadow-sm">
            <div class="card-body">
                <h6 class="card-title">Còn lại</h6>
                <h4 class="card-text fs-2">
                    @remaining.ToString("C", culture)
                </h4>
            </div>
        </div>
    </div>
</div>

<div class="row g-2 justify-content-center">
    @foreach (var jar in Model)
    {
        <div class="col-12">
            <div class="card shadow-sm">
                <div class="card-body d-flex align-items-center justify-content-between flex-wrap">
                    <div>
                        <h5 class="card-title mb-1">@jar.JarName</h5>
                        <div class="text-muted">
                            Số tiền còn lại: <br />
                            <span class="fs-5 fw-bold text-primary">
                                @jar.TotalIncome.ToString("C", culture)
                            </span>
                            <span class="fs-5 fw-bold text-warning">
                                - @jar.TotalExpense.ToString("C", culture)
                            </span>
                            <span class="fs-2 fw-bold text-nowrap @(jar.TotalAmount >= 0 ? "text-success" : "text-danger") mb-0">
                                = @jar.TotalAmount.ToString("C", culture)
                            </span>
                        </div>
                    </div>
                    <div class="mt-2">
                        <a href="@Url.Action("CreateExpense", "Transaction", new { jarId = jar.JarId })" class="btn btn-warning">
                            <i class="bi bi-cash-coin"></i>
                            Thêm chi tiêu
                        </a>
                        <a href="@Url.Action("ViewByJar", "Transaction", new { jarId = jar.JarId, fromDate =firstDayOfMonth.ToString("yyyy-MM-dd"), toDate = lastDayOfMonth.ToString("yyyy-MM-dd")  })" class="btn btn-primary">
                            <i class="bi bi-clock-history"></i>
                            Xem chi tiết
                        </a>
                    </div>
                </div>
            </div>
        </div>
    }
    <!-- Card Add Jar  -->
    <div style="cursor:pointer;" class="col-6 col-sm-2 btnAddJar">
        <div class="card shadow-sm">
            <div  class="card-body text-nowrap fs-4 d-flex text-center align-items-center justify-content-center flex-wrap py-3">
                <i class="bi bi-plus-circle me-2"></i> Thêm Hũ
            </div>
        </div>
    </div>
</div>